ec
git init : INITIALIZE 
git status : MENGECEK APAKAH FOLDER/FILE ADALAH REPOSITORI YANG SUDAH CONNECTED KE GITHUB
git add [FILENAME] / git add . : ADDING 1 FILE TO REPOSITORY (ANALOGY: PACKING TO A BOX)
git commit -m "commit message" : (ANALOGY CLOSING THE BOX), FILE SHOULD NOT BE EMPTY, "" IS COMMIT NAME
git reset --hard : UNDO THE COMMIT
git push : SENDING THE ADDED PACKAGED FILE INTO GITHUB
git pull : DOWNLOAD/MENGAMBIL FILE DARI GITHUB, HARUS ADA FILE YANG BARU DI REPOSITORY GITHUB
